language: common-lisp

env:
  matrix:
    - LISP=abcl
    - LISP=sbcl COVERALLS=true
    - LISP=ccl
#    - LISP=clisp  wait for cl-coveralls dependencies to support it
#    - LISP=ecl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;

script:
  - cl -l defclass-std -l prove -l cl-coveralls
       -e '(progn
            (setf prove:*debug-on-error* t
                  *debugger-hook* (lambda (c h)
                                    (declare (ignore c h))
                                    (uiop:quit -1)))
            (or (coveralls:with-coveralls (:exclude "t")
                  (prove:run :defclass-std-test))
                (uiop:quit -1)))'
