language: common-lisp
sudo: required
env:
  matrix:
    - LISP=abcl
    - LISP=sbcl COVERALLS=true
    - LISP=ccl
    - LISP=clisp
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    - env: LISP=abcl  # JVM build goes wrong too many times
    - env: LISP=clisp # wait for cl-coveralls dependencies to support it
    - env: LISP=cmucl # wait for CIM to support it
    - env: LISP=ecl   # wait for cl-coveralls dependencies to support it

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;

script:
  - cl -l defclass-std -l prove -l cl-coveralls
       -e '(progn
            (setf prove:*debug-on-error* t
                  *debugger-hook* (lambda (c h)
                                    (declare (ignore c h))
                                    (uiop:quit -1)))
            (or (coveralls:with-coveralls (:exclude "t")
                  (prove:run :defclass-std-test))
                (uiop:quit -1)))'
